build:
  - dnf install -y curl python38
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python3 get-pip.py
  script:
  - pip3 install -U --user -e .[cli]
  - CACHE_DIR=$(pwd)/.cache python3 ./shlaxfile.py build
  stage: build

build-itself:
  cache:
    key: cache
    paths: [.cache]
  image: shlax:$CI_COMMIT_SHORT_SHA
  script: python3 ./shlaxfile.py build
  stage: test

test:
  image: yourlabs/python
  stage: build
  script:
  - pip install -U --user -e .[test]
  - py.test -sv tests

pypi:
  image: yourlabs/python
  only: [tags]
  script: pypi-release
  stage: deploy
