build:
  image: yourlabs/shlax
  script: ./shlaxfile.py build
  stage: build
pypi:
  image: yourlabs/python
  only:
  - tags
  script: ./shlaxfile.py pypi
  stage: deploy
test:
  image: yourlabs/shlax
  script: ./shlaxfile.py test
  stage: test
