build:
  cache:
    key: cache
    paths: [.cache]
  image: yourlabs/shlax
  script: pip install -U --user -e .[cli] && CACHE_DIR=$(pwd)/.cache ./shlaxfile.py build
  stage: build

test:
  image: yourlabs/python
  stage: build
  script: pip install -U --user -e .[test] && py.test -sv tests

pypi:
  image: yourlabs/python
  only: [tags]
  script: pypi-release
  stage: deploy
